// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Generated Redfish schema subset
///
/// This module includes the autogenerated Rust types produced at build time by
/// `build.rs`. The set of compiled schemas is determined by:
/// - Enabled Cargo features in this crate (for example, `accounts`, `events`)
/// - The `features.toml` configuration, which maps features to specific Redfish
///   schemas and OEM extensions
///
/// The goal is to compile only the types required for the requested features,
/// keeping the library as lightweight as possible. These types are internal to
#[allow(clippy::doc_markdown)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::option_option)]
#[allow(clippy::missing_const_for_fn)]
#[allow(clippy::struct_field_names)]
#[allow(clippy::too_long_first_doc_paragraph)]
#[allow(missing_docs)]
pub mod redfish {
    include!(concat!(env!("OUT_DIR"), "/redfish.rs"));
}

#[cfg(all(test, feature = "resource-serialization"))]
mod tests {
    use super::redfish::resource::ItemOrCollection;
    use super::redfish::SettingsAnnotations;
    use serde_json::json;

    #[test]
    fn settings_annotations_preserve_resource_json() {
        assert_eq!(
            serde_json::to_value(SettingsAnnotations::default())
                .expect("empty annotations serialize"),
            json!({}),
        );
        for value in [
            json!({ "@odata.id": "/redfish/v1/Systems/1/Bios" }),
            json!({
                "@odata.id": "/redfish/v1/Systems/1/Bios",
                "@Redfish.Settings": {
                    "SettingsObject": { "@odata.id": "/redfish/v1/Systems/1/Bios/Settings" }
                },
                "@Redfish.SettingsApplyTime": {
                    "ApplyTime": "OnReset",
                    "MaintenanceWindowDurationInSeconds": 60
                }
            }),
        ] {
            let resource: ItemOrCollection = serde_json::from_value(value.clone())
                .expect("resource with settings annotations deserializes");
            assert_eq!(
                serde_json::to_value(resource).expect("resource serializes"),
                value,
            );
        }
    }
}
